// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: playerlist.proto

package responses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerEvent int32

const (
	PlayerEvent_EVENT_TYPE_PLAYER_LEAVE PlayerEvent = 0
	PlayerEvent_EVENT_TYPE_PLAYER_JOIN  PlayerEvent = 1
)

// Enum value maps for PlayerEvent.
var (
	PlayerEvent_name = map[int32]string{
		0: "EVENT_TYPE_PLAYER_LEAVE",
		1: "EVENT_TYPE_PLAYER_JOIN",
	}
	PlayerEvent_value = map[string]int32{
		"EVENT_TYPE_PLAYER_LEAVE": 0,
		"EVENT_TYPE_PLAYER_JOIN":  1,
	}
)

func (x PlayerEvent) Enum() *PlayerEvent {
	p := new(PlayerEvent)
	*p = x
	return p
}

func (x PlayerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_playerlist_proto_enumTypes[0].Descriptor()
}

func (PlayerEvent) Type() protoreflect.EnumType {
	return &file_playerlist_proto_enumTypes[0]
}

func (x PlayerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerEvent.Descriptor instead.
func (PlayerEvent) EnumDescriptor() ([]byte, []int) {
	return file_playerlist_proto_rawDescGZIP(), []int{0}
}

type PlayerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnyField *anypb.Any  `protobuf:"bytes,1,opt,name=any_field,json=anyField,proto3" json:"any_field,omitempty"`
	Type     PlayerEvent `protobuf:"varint,2,opt,name=type,proto3,enum=responses.PlayerEvent" json:"type,omitempty"`
	Id       string      `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name     string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Hometown string      `protobuf:"bytes,5,opt,name=hometown,proto3" json:"hometown,omitempty"`
	GangTag  string      `protobuf:"bytes,6,opt,name=gang_tag,json=gangTag,proto3" json:"gang_tag,omitempty"`
}

func (x *PlayerList) Reset() {
	*x = PlayerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_playerlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerList) ProtoMessage() {}

func (x *PlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_playerlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerList.ProtoReflect.Descriptor instead.
func (*PlayerList) Descriptor() ([]byte, []int) {
	return file_playerlist_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerList) GetAnyField() *anypb.Any {
	if x != nil {
		return x.AnyField
	}
	return nil
}

func (x *PlayerList) GetType() PlayerEvent {
	if x != nil {
		return x.Type
	}
	return PlayerEvent_EVENT_TYPE_PLAYER_LEAVE
}

func (x *PlayerList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerList) GetHometown() string {
	if x != nil {
		return x.Hometown
	}
	return ""
}

func (x *PlayerList) GetGangTag() string {
	if x != nil {
		return x.GangTag
	}
	return ""
}

var File_playerlist_proto protoreflect.FileDescriptor

var file_playerlist_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x61, 0x6e, 0x79, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x08, 0x61, 0x6e, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x6d, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x6d, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6e, 0x67, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x6e, 0x67, 0x54, 0x61,
	0x67, 0x2a, 0x46, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x17, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x00, 0x12, 0x1a, 0x0a,
	0x16, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x45, 0x52, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x3b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_playerlist_proto_rawDescOnce sync.Once
	file_playerlist_proto_rawDescData = file_playerlist_proto_rawDesc
)

func file_playerlist_proto_rawDescGZIP() []byte {
	file_playerlist_proto_rawDescOnce.Do(func() {
		file_playerlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_playerlist_proto_rawDescData)
	})
	return file_playerlist_proto_rawDescData
}

var file_playerlist_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_playerlist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_playerlist_proto_goTypes = []interface{}{
	(PlayerEvent)(0),   // 0: responses.PlayerEvent
	(*PlayerList)(nil), // 1: responses.PlayerList
	(*anypb.Any)(nil),  // 2: google.protobuf.Any
}
var file_playerlist_proto_depIdxs = []int32{
	2, // 0: responses.PlayerList.any_field:type_name -> google.protobuf.Any
	0, // 1: responses.PlayerList.type:type_name -> responses.PlayerEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_playerlist_proto_init() }
func file_playerlist_proto_init() {
	if File_playerlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_playerlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playerlist_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playerlist_proto_goTypes,
		DependencyIndexes: file_playerlist_proto_depIdxs,
		EnumInfos:         file_playerlist_proto_enumTypes,
		MessageInfos:      file_playerlist_proto_msgTypes,
	}.Build()
	File_playerlist_proto = out.File
	file_playerlist_proto_rawDesc = nil
	file_playerlist_proto_goTypes = nil
	file_playerlist_proto_depIdxs = nil
}
